version: "3.8"
services:
   worker:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID
      API_HASH: $API_HASH
      CHANNELS: $CHANNELS
      ADMINS: $ADMINS
      LOG_CHANNEL: $LOG_CHANNEL
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_URI: $DATABASE_URI
      PICS: $PICS
      AUTH_CHANNEL: $AUTH_CHANNEL
      AUTH_USERS: $AUTH_USERS
      COLLECTION_NAME: $COLLECTION_NAME
      CUSTOM_FILE_CAPTION: $CUSTOM_FILE_CAPTION
      P_TTI_SHOW_OFF: $P_TTI_SHOW_OFF
      SINGLE_BUTTON: $SINGLE_BUTTON
      SUPPORT_CHAT: $SUPPORT_CHAT
      USE_CAPTION_FILTER: $USE_CAPTION_FILTER
      CACHE_TIME: $CACHE_TIME
      IMDB: $IMDB
